# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
puts "Creating Seeds"

Movie.create(title: "Wonder Woman 1984", overview: "Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s", poster_url: "https://image.tmdb.org/t/p/original/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg", rating: 6.9)
Movie.create(title: "The Shawshank Redemption", overview: "Framed in the 1940s for double murder, upstanding banker Andy Dufresne begins a new life at the Shawshank prison", poster_url: "https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg", rating: 8.7)
Movie.create(title: "Titanic", overview: "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic.", poster_url: "https://image.tmdb.org/t/p/original/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg", rating: 7.9)
Movie.create(title: "Ocean's Eight", overview: "Debbie Ocean, a criminal mastermind, gathers a crew of female thieves to pull off the heist of the century.", poster_url: "https://image.tmdb.org/t/p/original/MvYpKlpFukTivnlBhizGbkAe3v.jpg", rating: 7.0)
Movie.create(title: "The Batman", overview: "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/74xTEgt7R36Fpooo50r9T25onhq.jpg", rating: 7.9)
Movie.create(title: "Turning Red", overview: "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist when she gets too excited, she transforms into a giant red panda.", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg", rating: 7.5)
Movie.create(title: "Morbius", overview: "Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Michael Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/7gmOjg7lQXGLW8wX31ry1IdIY07.jpg", rating: 5.8)
Movie.create(title: "Jackass Forever", overview: "Celebrate the joy of a perfectly executed shot to the groin as Johnny Knoxville, Steve-O and the rest of the gang return alongside some newcomers for one final round of hilarious, wildly absurd and often dangerous displays of stunts and comedy.", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/ugIdyvtAzHWOguD91UjHKoAvfum.jpg", rating: 6.9)
Movie.create(title: "Doctor Strange", overview: "After his career is destroyed, a brilliant but arrogant surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg", rating: 7.4)
Movie.create(title: "Venom: Let There Be Carnage", overview: "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg", rating: 7.0)
Movie.create(title: "Bull Shark", overview: "A hungry shark begins feeding on unsuspecting lake goers in a small Texas town.", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/wGE4ImqYjJZQi3xFu4I2OLm8m0w.jpg", rating: 4.7)
Movie.create(title: "Space Jam", overview: "Jokes fly as the Tune Squad takes on the Nerdlucks in a hardcourt game to decide if the Looney Tunes remain here... or become attractions at a far-off galactic off-ramp called Moron Mountain. The Nerdlucks have a monstrous secret weapon: they've stolen the skills of top NBA stars like Charles Barkley and Patrick Ewing and become Monstars. But that's not all, folks. The Tune Squad’s secret weapon just happens to be the finest player in this or any other universe. He's outta this world. So's the fun.", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/7Jd4M4vc6IvzL2sLDKkjWswF5rO.jpg", rating: 6.9)
Movie.create(title: "Avatar", overview: "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg", rating: 7.5)
Movie.create(title: "Fury", overview: "In the last months of World War II, as the Allies make their final push in the European theatre, a battle-hardened U.S. Army sergeant named 'Wardaddy' commands a Sherman tank called 'Fury' and its five-man crew on a deadly mission behind enemy lines. Outnumbered and outgunned, Wardaddy and his men face overwhelming odds in their heroic attempts to strike at the heart of Nazi Germany.", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/pfte7wdMobMF4CVHuOxyu6oqeeA.jpg", rating: 7.5)
Movie.create(title: "Eternals", overview: "The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind’s most ancient enemy, the Deviants.", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/bcCBq9N1EMo3daNIjWJ8kYvrQm6.jpg", rating: 7.1)
Movie.create(title: "Mortal Kombat", overview: "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/nkayOAUBUu4mMvyNf9iHSUiPjF1.jpg", rating: 7.2)
Movie.create(title: "Clifford The Big Red Dog", overview: "As Emily struggles to fit in at home and at school, she discovers a small red puppy who is destined to become her best friend. When Clifford magically undergoes one heck of a growth spurt, becomes a gigantic dog and attracts the attention of a genetics company, Emily and her Uncle Casey have to fight the forces of greed as they go on the run across New York City. Along the way, Clifford affects the lives of everyone around him and teaches Emily and her uncle the true meaning of acceptance and unconditional love.", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/oifhfVhUcuDjE61V5bS5dfShQrm.jpg", rating: 7.3)
Movie.create(title: "Pokemon Detective Pikcahu", overview: "In a world where people collect pocket-size monsters (Pokémon) to do battle, a boy comes across an intelligent monster who seeks to be a detective.", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/wgQ7APnFpf1TuviKHXeEe3KnsTV.jpg", rating: 7.0)
Movie.create(title: "The Maze Runner", overview: "Set in a post-apocalyptic world, young Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow “runners” for a shot at escape.", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/ode14q7WtDugFDp78fo9lCsmay9.jpg", rating: 7.2)
Movie.create(title: "Toy Story", overview: "Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.", poster_url: "https://www.themoviedb.org/t/p/w220_and_h330_face/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg", rating: 8.0)
Movie.create(title: "Thor Love and Thunder", overview: "Thor goes on a journey unlike anything he’s ever faced — a quest for inner peace. But his retirement is interrupted by a galactic killer known as Gorr the God Butcher, who seeks the extinction of the gods. To combat the threat, Thor enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who — to Thor’s surprise — inexplicably wields his magical hammer, Mjolnir, as the Mighty Thor. Together, they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/cOkx3uu5FVgC902Q6Y3MxLpBWbX.jpg", rating: 10)
Movie.create(title: "The Lion King", overview: "A young lion prince is cast out of his pride by his cruel uncle, who claims he killed his father. While the uncle rules with an iron paw, the prince grows up beyond the Savannah, living by a philosophy: No worries for the rest of your days. But when his past comes to haunt him, the young prince must decide his fate: Will he remain an outcast or face his demons and become what he needs to be?", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg", rating: 8.3)
Movie.create(title: "It Chapter Two", overview: "27 years after overcoming the malevolent supernatural entity Pennywise, the former members of the Losers' Club, who have grown up and moved away from Derry, are brought back together by a devastating phone call.", poster_url: "https://www.themoviedb.org/t/p/w220_and_h330_face/zfE0R94v1E8cuKAerbskfD3VfUt.jpg", rating: 6.9)
Movie.create(title: "The Hangover", overview: "When three friends finally come to after a raucous night of bachelor-party revelry, they find a baby in the closet and a tiger in the bathroom. But they can't seem to locate their best friend, Doug – who's supposed to be tying the knot. Launching a frantic search for Doug, the trio perseveres through a nasty hangover to try to make it to the church on time.", poster_url: "https://www.themoviedb.org/t/p/w220_and_h330_face/jjCPcxw7QCmFPYM1t3BThdEawJK.jpg", rating: 7.3)
Movie.create(title: "The Adam Project", overview: "After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self on a mission to save the future.", poster_url: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/wFjboE0aFZNbVOF05fzrka9Fqyx.jpg", rating: 7.0)

puts "Seeds created"
